"""
Layout and page template classes for tearsheet compilation.
Includes NumberedCanvas for dynamic two-pass page numbering and footers.
"""

from datetime import datetime

from reportlab.pdfgen import canvas

from src.reports.styles import (
    A4_WIDTH,
    BORDER_LIGHT,
    MARGIN_POINTS,
    TEXT_LIGHT,
)


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to compute total page count and draw running footers.
    Useful for strict page budgeting (e.g. 'Page X of Y').
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        # Save state for the second pass
        """Showpage for NumberedCanvas."""
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        """Save for NumberedCanvas."""
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decor(num_pages)
            super().showPage()
        super().save()

    def draw_page_decor(self, page_count):
        """Draw page decor for NumberedCanvas."""
        self.saveState()

        # Draw thin divider line above footer
        self.setStrokeColor(BORDER_LIGHT)
        self.setLineWidth(0.5)
        self.line(MARGIN_POINTS, 35, A4_WIDTH - MARGIN_POINTS, 35)

        # Set text styles
        self.setFont("Helvetica", 8)
        self.setFillColor(TEXT_LIGHT)

        # Left footer: Generated by
        self.drawString(
            MARGIN_POINTS, 22, "Generated by N100 Financial Intelligence Platform"
        )

        # Center footer: Compilation date
        today_str = datetime.now().strftime("%Y-%m-%d")
        self.drawCentredString(A4_WIDTH / 2.0, 22, f"Date: {today_str}")

        # Right footer: Page numbering
        self.drawRightString(
            A4_WIDTH - MARGIN_POINTS, 22, f"Page {self._pageNumber} of {page_count}"
        )

        self.restoreState()
