"""
Report builder utilities for N100 Portfolio Summary Tearsheets.
Defines NumberedCanvas and flowable layouts for report pages.
"""

from datetime import datetime

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfgen import canvas
from reportlab.platypus import Paragraph, Spacer, Table, TableStyle

from src.reports.report_styles import (
    A4_HEIGHT,
    A4_WIDTH,
    BORDER_LIGHT,
    CON_RED,
    GREY_SLATE,
    MARGIN_POINTS,
    NAVY_PRIMARY,
    PRINTABLE_WIDTH,
    PRO_GREEN,
    TEXT_LIGHT,
    TEXT_NEUTRAL,
    badge_style,
    bullet_heading_con,
    bullet_heading_pro,
    bullet_style,
    kpi_label_style,
    kpi_unit_style,
    kpi_value_style,
    meta_style,
    meta_subtitle_style,
    section_heading_style,
    subtitle_style,
    title_style,
    trend_arrow_style,
    trend_label_style,
    val_label_style,
    val_value_style,
)

# Badge Mappings
ALLOC_BADGE_COLORS = {
    "Reinvestor": ("#E8F5E9", "#2E7D32", "REINVESTOR"),
    "Shareholder Returns": ("#E8EAF6", "#1A237E", "SHAREHOLDER RETURNS"),
    "Cash Accumulator": ("#E3F2FD", "#0D47A1", "CASH ACCUMULATOR"),
    "Distress Signal": ("#FFEBEE", "#B71C1C", "DISTRESS SIGNAL"),
    "Growth Funded by Debt": ("#FFF3E0", "#E65100", "GROWTH FUNDED BY DEBT"),
    "Liquidating Assets": ("#EFEBE9", "#4E342E", "LIQUIDATING ASSETS"),
    "Pre-Revenue": ("#ECEFF1", "#37474F", "PRE-REVENUE"),
    "Mixed": ("#E0F7FA", "#006064", "MIXED"),
}

VAL_BADGE_COLORS = {
    "Discount": ("#E8F5E9", "#2E7D32", "DISCOUNT"),
    "Caution": ("#FFEBEE", "#B71C1C", "CAUTION"),
    "Fair": ("#F1F5F9", "#475569", "FAIR"),
}


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to compute total page count and draw running footers.
    Useful for strict page budgeting (e.g. 'Page X of Y').
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        # Save state for the second pass
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decor(num_pages)
            super().showPage()
        super().save()

    def draw_page_decor(self, page_count):
        self.saveState()

        # Draw thin divider line above footer
        self.setStrokeColor(BORDER_LIGHT)
        self.setLineWidth(0.5)
        self.line(MARGIN_POINTS, 28, A4_WIDTH - MARGIN_POINTS, 28)

        # Set text styles
        self.setFont("Helvetica", 7.5)
        self.setFillColor(TEXT_LIGHT)

        # Left footer: Generated by
        self.drawString(
            MARGIN_POINTS,
            16,
            "Nifty 100 Financial Intelligence Platform | Executive Portfolio Summary",
        )

        # Center footer: Compilation date
        today_str = datetime.now().strftime("%Y-%m-%d")
        self.drawCentredString(A4_WIDTH / 2.0, 16, f"Compiled: {today_str}")

        # Right footer: Page numbering
        self.drawRightString(
            A4_WIDTH - MARGIN_POINTS, 16, f"Page {self._pageNumber} of {page_count}"
        )

        self.restoreState()


def build_header(
    company_name: str, ticker: str, sector: str, industry: str, latest_year: str
) -> Table:
    """Creates a custom navy header bar for tearsheet pages."""
    col1_flowables = [
        Paragraph(f"<b>{company_name.upper()}</b>", title_style),
        Spacer(1, 2),
        Paragraph(
            f"NSE Ticker: {ticker} | Sector: {sector} | Industry: {industry}",
            subtitle_style,
        ),
    ]

    col2_flowables = [
        Paragraph("<b>EXECUTIVE PORTFOLIO TEARSHEET</b>", meta_style),
        Spacer(1, 2),
        Paragraph(f"Financial Year: {latest_year}", meta_subtitle_style),
    ]

    header_table = Table([[col1_flowables, col2_flowables]], colWidths=[360, 163])
    header_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), NAVY_PRIMARY),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ]
        )
    )
    return header_table


def make_kpi_card(label: str, val_str: str, unit: str, color_hex: str) -> list:
    """Builds the flowable elements for a single KPI Card."""
    label_p = Paragraph(f"<b>{label}</b>", kpi_label_style)
    value_p = Paragraph(
        f"<font color='{color_hex}'><b>{val_str}</b></font>", kpi_value_style
    )
    unit_p = Paragraph(unit, kpi_unit_style)
    return [label_p, Spacer(1, 2), value_p, Spacer(1, 1), unit_p]


def build_kpi_table(latest_ratios: pd.Series) -> Table:
    """Creates a 2x3 table of KPI Cards from the latest ratio data."""

    # Helper to check null
    def is_null(val):
        return pd.isnull(val) or val is None

    # 1. ROE
    roe_val = latest_ratios.get("return_on_equity_pct")
    if is_null(roe_val):
        roe_str, roe_color = "N/A", TEXT_LIGHT.hexval()
    else:
        roe_str = f"{roe_val:.1f}%"
        roe_color = (
            PRO_GREEN.hexval()
            if roe_val > 15
            else (CON_RED.hexval() if roe_val < 0 else NAVY_PRIMARY.hexval())
        )
    card_roe = make_kpi_card("Return on Equity (ROE)", roe_str, "Percentage", roe_color)

    # 2. ROCE
    roce_val = latest_ratios.get("return_on_capital_employed_pct")
    if is_null(roce_val):
        roce_str, roce_color = "N/A", TEXT_LIGHT.hexval()
    else:
        roce_str = f"{roce_val:.1f}%"
        roce_color = (
            PRO_GREEN.hexval()
            if roce_val > 15
            else (CON_RED.hexval() if roce_val < 0 else NAVY_PRIMARY.hexval())
        )
    card_roce = make_kpi_card(
        "Return on Capital (ROCE)", roce_str, "Percentage", roce_color
    )

    # 3. NPM
    npm_val = latest_ratios.get("net_profit_margin_pct")
    if is_null(npm_val):
        npm_str, npm_color = "N/A", TEXT_LIGHT.hexval()
    else:
        npm_str = f"{npm_val:.1f}%"
        npm_color = (
            PRO_GREEN.hexval()
            if npm_val > 12
            else (CON_RED.hexval() if npm_val < 0 else NAVY_PRIMARY.hexval())
        )
    card_npm = make_kpi_card(
        "Net Profit Margin (NPM)", npm_str, "Percentage", npm_color
    )

    # 4. Debt to Equity
    de_val = latest_ratios.get("debt_to_equity")
    if is_null(de_val):
        de_str, de_color = "N/A", TEXT_LIGHT.hexval()
    else:
        de_str = f"{de_val:.2f}x"
        de_color = (
            PRO_GREEN.hexval()
            if de_val < 0.5
            else (CON_RED.hexval() if de_val > 1.5 else NAVY_PRIMARY.hexval())
        )
    card_de = make_kpi_card("Debt to Equity (D/E)", de_str, "Leverage Ratio", de_color)

    # 5. Revenue CAGR (5Y)
    cagr_val = latest_ratios.get("revenue_cagr_5yr")
    if is_null(cagr_val):
        cagr_str, cagr_color = "N/A", TEXT_LIGHT.hexval()
    else:
        cagr_str = f"{cagr_val:.1f}%"
        cagr_color = (
            PRO_GREEN.hexval()
            if cagr_val > 10
            else (CON_RED.hexval() if cagr_val < 0 else NAVY_PRIMARY.hexval())
        )
    card_cagr = make_kpi_card("Revenue CAGR (5Y)", cagr_str, "Growth Rate", cagr_color)

    # 6. FCF
    fcf_val = latest_ratios.get("free_cash_flow_cr")
    if is_null(fcf_val):
        fcf_str, fcf_color = "N/A", TEXT_LIGHT.hexval()
    else:
        fcf_str = f"\u20b9{fcf_val:,.0f} Cr"
        fcf_color = (
            PRO_GREEN.hexval()
            if fcf_val > 0
            else (CON_RED.hexval() if fcf_val < 0 else NAVY_PRIMARY.hexval())
        )
    card_fcf = make_kpi_card(
        "Free Cash Flow (FCF)", fcf_str, "INR in Crores", fcf_color
    )

    # Arrange in a 2x3 Grid Table
    data = [[card_roe, card_roce, card_npm], [card_de, card_cagr, card_fcf]]

    col_w = PRINTABLE_WIDTH / 3.0
    kpi_table = Table(data, colWidths=[col_w, col_w, col_w])
    kpi_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), GREY_SLATE),
                ("GRID", (0, 0), (-1, -1), 1.0, colors.white),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    return kpi_table


def calculate_trend(latest: float, prev: float, is_debt: bool = False) -> tuple:
    """Computes arrow direction, color, and trend text label based on relative changes."""
    if pd.isnull(latest) or pd.isnull(prev) or latest is None or prev is None:
        return "→", TEXT_LIGHT, "Stable (N/A)"

    if prev == 0.0:
        rel_change = latest - prev
    else:
        rel_change = (latest - prev) / abs(prev)

    if abs(rel_change) <= 0.02:
        return "→", TEXT_LIGHT, "Stable"

    if is_debt:
        # Debt ratio: lower is better
        if rel_change < -0.02:
            return "↑", PRO_GREEN, "Improved"
        else:
            return "↓", CON_RED, "Declined"
    else:
        # Other ratios: higher is better
        if rel_change > 0.02:
            return "↑", PRO_GREEN, "Improved"
        else:
            return "↓", CON_RED, "Declined"


def make_trend_cell(
    label: str,
    latest_val: float,
    prev_val: float,
    arrow: str,
    color: colors.Color,
    label_text: str,
    is_pct: bool = False,
    is_curr: bool = False,
) -> Paragraph:
    """Builds a formatted Paragraph with YoY trend information."""

    def fmt(val):
        if pd.isnull(val) or val is None:
            return "N/A"
        if is_curr:
            return f"\u20b9{val:,.0f}Cr"
        if is_pct:
            return f"{val:.1f}%"
        return f"{val:.2f}x" if "D/E" in label else f"{val:.2f}"

    l_str = fmt(latest_val)
    p_str = fmt(prev_val)

    text_html = (
        f"<b>{label} YoY Trend</b><br/>"
        f"<font size='7' color='{TEXT_LIGHT.hexval()}'>{p_str} &rarr; {l_str}</font><br/>"
        f"<font color='{color.hexval()}'><b>{arrow} {label_text}</b></font>"
    )
    return Paragraph(text_html, trend_label_style)


def build_trend_table(latest_ratios: pd.Series, prev_ratios: pd.Series) -> Table:
    """Creates a 2x3 grid displaying YoY trend indicators for all 6 KPIs."""
    # ROE
    arrow, color, label = calculate_trend(
        latest_ratios.get("return_on_equity_pct"),
        prev_ratios.get("return_on_equity_pct"),
    )
    cell_roe = make_trend_cell(
        "ROE",
        latest_ratios.get("return_on_equity_pct"),
        prev_ratios.get("return_on_equity_pct"),
        arrow,
        color,
        label,
        is_pct=True,
    )

    # ROCE
    arrow, color, label = calculate_trend(
        latest_ratios.get("return_on_capital_employed_pct"),
        prev_ratios.get("return_on_capital_employed_pct"),
    )
    cell_roce = make_trend_cell(
        "ROCE",
        latest_ratios.get("return_on_capital_employed_pct"),
        prev_ratios.get("return_on_capital_employed_pct"),
        arrow,
        color,
        label,
        is_pct=True,
    )

    # NPM
    arrow, color, label = calculate_trend(
        latest_ratios.get("net_profit_margin_pct"),
        prev_ratios.get("net_profit_margin_pct"),
    )
    cell_npm = make_trend_cell(
        "NPM",
        latest_ratios.get("net_profit_margin_pct"),
        prev_ratios.get("net_profit_margin_pct"),
        arrow,
        color,
        label,
        is_pct=True,
    )

    # Debt-to-Equity
    arrow, color, label = calculate_trend(
        latest_ratios.get("debt_to_equity"),
        prev_ratios.get("debt_to_equity"),
        is_debt=True,
    )
    cell_de = make_trend_cell(
        "Debt/Equity",
        latest_ratios.get("debt_to_equity"),
        prev_ratios.get("debt_to_equity"),
        arrow,
        color,
        label,
    )

    # Rev CAGR
    arrow, color, label = calculate_trend(
        latest_ratios.get("revenue_cagr_5yr"), prev_ratios.get("revenue_cagr_5yr")
    )
    cell_cagr = make_trend_cell(
        "Rev CAGR",
        latest_ratios.get("revenue_cagr_5yr"),
        prev_ratios.get("revenue_cagr_5yr"),
        arrow,
        color,
        label,
        is_pct=True,
    )

    # FCF
    arrow, color, label = calculate_trend(
        latest_ratios.get("free_cash_flow_cr"), prev_ratios.get("free_cash_flow_cr")
    )
    cell_fcf = make_trend_cell(
        "Free Cash Flow",
        latest_ratios.get("free_cash_flow_cr"),
        prev_ratios.get("free_cash_flow_cr"),
        arrow,
        color,
        label,
        is_curr=True,
    )

    data = [[cell_roe, cell_roce, cell_npm], [cell_de, cell_cagr, cell_fcf]]

    col_w = PRINTABLE_WIDTH / 3.0
    trend_table = Table(data, colWidths=[col_w, col_w, col_w])
    trend_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), GREY_SLATE),
                ("GRID", (0, 0), (-1, -1), 1.0, colors.white),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    return trend_table


def build_pros_cons_table(pros: list, cons: list) -> Table:
    """Renders a side-by-side list of strengths and risks."""
    pros_show = pros[:3]
    cons_show = cons[:3]

    if not pros_show:
        pros_show = ["No major financial strengths identified."]
    if not cons_show:
        cons_show = ["No major financial concerns identified."]

    pro_flowables = [
        Paragraph("<b>Key Financial Strengths (Pros)</b>", bullet_heading_pro)
    ]
    for p_text in pros_show:
        bullet_html = (
            f"<font color='{PRO_GREEN.hexval()}'><b>&#9656;</b></font> {p_text}"
        )
        pro_flowables.append(Paragraph(bullet_html, bullet_style))

    con_flowables = [
        Paragraph("<b>Key Financial Concerns (Cons)</b>", bullet_heading_con)
    ]
    for c_text in cons_show:
        bullet_html = f"<font color='{CON_RED.hexval()}'><b>&#9656;</b></font> {c_text}"
        con_flowables.append(Paragraph(bullet_html, bullet_style))

    pros_cons = Table([[pro_flowables, con_flowables]], colWidths=[256, 267])
    pros_cons.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    return pros_cons


def build_allocation_badge(label: str) -> Table:
    """Builds a beautiful colored capital allocation badge."""
    bg_color, text_color, badge_text = ALLOC_BADGE_COLORS.get(
        label, ("#ECEFF1", "#37474F", str(label).upper())
    )

    badge_para_style = ParagraphStyle(
        "AllocBadgeInner",
        parent=badge_style,
        textColor=colors.HexColor(text_color),
        fontSize=8,
    )

    badge_cell = Paragraph(f"<b>{badge_text}</b>", badge_para_style)
    badge_table = Table([[badge_cell]], colWidths=[150])
    badge_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(bg_color)),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("BOX", (0, 0), (-1, -1), 1.0, colors.HexColor(text_color)),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return badge_table


def build_valuation_badge(label: str) -> Table:
    """Builds a beautiful colored valuation category badge."""
    bg_color, text_color, badge_text = VAL_BADGE_COLORS.get(
        label, ("#F1F5F9", "#475569", str(label).upper())
    )

    badge_para_style = ParagraphStyle(
        "ValBadgeInner",
        parent=badge_style,
        textColor=colors.HexColor(text_color),
        fontSize=8,
    )

    badge_cell = Paragraph(f"<b>{badge_text}</b>", badge_para_style)
    badge_table = Table([[badge_cell]], colWidths=[70])
    badge_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(bg_color)),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("BOX", (0, 0), (-1, -1), 1.0, colors.HexColor(text_color)),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return badge_table


def build_allocation_valuation_table(
    alloc_label: str,
    fcf_yield: float,
    pe_ratio: float,
    sector_median_pe: float,
    val_flag: str,
) -> Table:
    """Renders Capital Allocation patterns and Valuation summary metrics."""
    # Left side: Capital Allocation
    alloc_flowables = [
        Paragraph("<b>CAPITAL ALLOCATION PATTERN</b>", section_heading_style),
        Spacer(1, 4),
        build_allocation_badge(alloc_label),
        Spacer(1, 4),
        Paragraph(
            f"<font color='{TEXT_LIGHT.hexval()}'>Latest classification based on cash flow trends.</font>",
            val_value_style,
        ),
    ]

    # Right side: Valuation Highlights
    fcf_yield_str = (
        f"{fcf_yield:.2f}%"
        if not pd.isnull(fcf_yield) and fcf_yield is not None
        else "N/A"
    )
    pe_str = (
        f"{pe_ratio:.2f}" if not pd.isnull(pe_ratio) and pe_ratio is not None else "N/A"
    )
    sec_pe_str = (
        f"{sector_median_pe:.2f}"
        if not pd.isnull(sector_median_pe) and sector_median_pe is not None
        else "N/A"
    )

    val_table_data = [
        [
            Paragraph("<b>FCF Yield:</b>", val_label_style),
            Paragraph(fcf_yield_str, val_value_style),
        ],
        [
            Paragraph("<b>P/E Ratio:</b>", val_label_style),
            Paragraph(f"{pe_str} (Sector Med: {sec_pe_str})", val_value_style),
        ],
    ]
    val_info_table = Table(val_table_data, colWidths=[70, 110])
    val_info_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
                ("TOPPADDING", (0, 0), (-1, -1), 2),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )

    val_flowables = [
        Paragraph("<b>VALUATION HIGHLIGHTS</b>", section_heading_style),
        Spacer(1, 4),
        Table([[val_info_table, build_valuation_badge(val_flag)]], colWidths=[180, 80]),
    ]
    val_flowables[2].setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )

    av_table = Table([[alloc_flowables, val_flowables]], colWidths=[256, 267])
    av_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    return av_table
